export const APP_LANGUAGES = [
  { value: 'en', label: '🇬🇧 EN - English' },
  { value: 'fr', label: '🇫🇷 FR - Français' },
  { value: 'es', label: '🇪🇸 ES - Español' },
  { value: 'es-mx', label: '🇲🇽 ES-MX - Español (México)' },
  { value: 'it', label: '🇮🇹 IT - Italiano' },
  { value: 'pt', label: '🇵🇹 PT - Português' },
  { value: 'pt-br', label: '🇧🇷 PT-BR - Português (Brasil)' },
  { value: 'pt-pt', label: '🇵🇹 PT-PT - Português (Portugal)' },
  { value: 'de', label: '🇩🇪 DE - Deutsch' },
  { value: 'nl', label: '🇳🇱 NL - Nederlands' },
  { value: 'pl', label: '🇵🇱 PL - Polski' },
  { value: 'ru', label: '🇷🇺 RU - Русский' },
  { value: 'ja', label: '🇯🇵 JA - 日本語' },
  { value: 'ko', label: '🇰🇷 KO - 한국어' },
  { value: 'zh-tw', label: '🇹🇼 ZH-TW - 繁體中文' },
  { value: 'id', label: '🇮🇩 ID - Bahasa Indonesia' },
  { value: 'th', label: '🇹🇭 TH - ไทย' },
  { value: 'zh-cn', label: '🇨🇳 ZH-CN - 简体中文' },
  { value: 'sv', label: '🇸🇪 SV - Svenska' },
]
